#ifndef __KVM_ASM_OFFSETS_H__
#define __KVM_ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 */


#define VMX_spec_ctrl 6984 /* offsetof(struct vcpu_vmx, spec_ctrl) */

#endif
