/* AUTO-GENERATED by quantizer/quantizer.py — do not edit by hand.
 *
 * Toy decision tree with 3 nodes (depth 1) for smoke-testing.
 * Replace with output of quantizer.py once a real model is trained.
 *
 * Tree logic:
 *   if deadline[task 0] < deadline[task 1]:
 *       pick task 0
 *   else:
 *       pick task 1
 *
 * Feature indices (see dtree.h):
 *   HDR_SLOTS=20, TASK_FIELDS=3
 *   deadline of task 0 → index 22  (20 + 0*3 + 2)
 *   deadline of task 1 → index 25  (20 + 1*3 + 2)
 */
#pragma once

#include "include/dtree.h"

/*
 * Node layout: { left, right, feature, threshold, value }
 *   feature = DTREE_LEAF_SENTINEL (-1) for leaves
 */
static const struct dtree_node MODEL_NODES[] = {
	/* node 0 — root: split on deadline of task 0 vs task 1 */
	{ .left = 1, .right = 2, .feature = 22, .threshold = 0, .value = 0 },
	/* node 1 — leaf: pick task 0 */
	{ .left = -1, .right = -1, .feature = -1, .threshold = 0, .value = 0 },
	/* node 2 — leaf: pick task 1 */
	{ .left = -1, .right = -1, .feature = -1, .threshold = 0, .value = 1 },
};

/*
 * NOTE: The placeholder root threshold is 0, which always sends to the
 * right child (task 1). quantizer.py will replace this with the real
 * threshold learned from training data.
 */

#define MODEL_N_NODES  (sizeof(MODEL_NODES) / sizeof(MODEL_NODES[0]))

static const struct dtree_model THE_MODEL = {
	.nodes   = MODEL_NODES,
	.n_nodes = MODEL_N_NODES,
};
