#!/usr/bin/env python3
"""
quantizer.py — Export a trained sklearn DecisionTreeClassifier to a C header
that can be compiled in both userspace (test harness) and a kernel module.

Usage:
    python3 quantizer.py --model model.pkl --output ../model/model_weights.h

The script reads a pickled sklearn DecisionTreeClassifier, extracts the tree
structure, and emits a C file with a flat array of struct dtree_node values.

Feature vector layout (must match include/dtree.h and kernel/sched/fair.c):
    features[0  .. 19]                  header slots (global fields)
    features[20 + i*2 + 0]              pid      of task i
    features[20 + i*2 + 1]              vruntime of task i

Threshold quantization:
    sklearn stores thresholds as float64.  Because vruntime / deadline values
    are raw nanoseconds (u64 up to ~10^13), they fit exactly in float64
    (which has 53 mantissa bits ≈ 9×10^15).  We cast directly to u64 via
    int() + rounding, with no loss of information.
"""

import argparse
import pickle
import textwrap
from pathlib import Path

HEADER_SLOTS   = 20
TASK_FIELDS    = 2
LEAF_SENTINEL  = -1   # sklearn TREE_LEAF


def load_model(path: str):
    with open(path, "rb") as f:
        return pickle.load(f)


def quantize_threshold(value: float) -> int:
    """
    Convert a sklearn float64 threshold to a u64 integer.

    sklearn sometimes emits -2.0 as the threshold on leaf nodes.
    For non-leaf splits on scheduler features (nanoseconds), the value
    is always non-negative, so we clamp to 0 as a floor.
    """
    if value < 0:
        return 0
    return int(value + 0.5)   # round to nearest integer


def majority_class(node_id: int, tree) -> int:
    """Return the class with the highest sample count at this node."""
    return int(tree.value[node_id].argmax())


def emit_header(tree, n_classes: int, output_path: str) -> None:
    nodes      = []
    n_nodes    = tree.node_count
    children_l = tree.children_left
    children_r = tree.children_right
    features   = tree.feature
    thresholds = tree.threshold

    for i in range(n_nodes):
        is_leaf = children_l[i] == LEAF_SENTINEL
        node = {
            "left":      int(children_l[i]),
            "right":     int(children_r[i]),
            "feature":   LEAF_SENTINEL if is_leaf else int(features[i]),
            "threshold": 0 if is_leaf else quantize_threshold(thresholds[i]),
            "value":     majority_class(i, tree) if is_leaf else 0,
        }
        nodes.append(node)

    lines = []
    lines.append("/* AUTO-GENERATED by quantizer/quantizer.py — do not edit by hand. */")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include \"include/dtree.h\"")
    lines.append("")
    lines.append(f"/* Tree: {n_nodes} nodes, {n_classes} classes, "
                 f"max depth inferred from shape. */")
    lines.append("static const struct dtree_node MODEL_NODES[] = {")

    for i, nd in enumerate(nodes):
        lines.append(
            f"\t/* {i:4d} */ "
            f"{{ .left={nd['left']:6d}, .right={nd['right']:6d}, "
            f".feature={nd['feature']:4d}, "
            f".threshold={nd['threshold']:20d}ULL, "
            f".value={nd['value']:4d} }},"
        )

    lines.append("};")
    lines.append("")
    lines.append("#define MODEL_N_NODES  "
                 "(sizeof(MODEL_NODES) / sizeof(MODEL_NODES[0]))")
    lines.append("")
    lines.append("static const struct dtree_model THE_MODEL = {")
    lines.append("\t.nodes   = MODEL_NODES,")
    lines.append("\t.n_nodes = MODEL_N_NODES,")
    lines.append("};")
    lines.append("")

    Path(output_path).write_text("\n".join(lines))
    print(f"Wrote {n_nodes} nodes → {output_path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--model",  required=True, help="Path to pickled sklearn model (.pkl)")
    parser.add_argument("--output", required=True, help="Output C header path")
    args = parser.parse_args()

    clf = load_model(args.model)

    # Validate it's a DecisionTreeClassifier
    cls_name = type(clf).__name__
    if "DecisionTree" not in cls_name:
        print(f"WARNING: expected DecisionTreeClassifier, got {cls_name}")

    tree      = clf.tree_
    n_classes = clf.n_classes_

    print(f"Model: {cls_name}")
    print(f"  nodes    : {tree.node_count}")
    print(f"  max_depth: {clf.get_depth()}")
    print(f"  classes  : {n_classes}  ({clf.classes_.tolist()})")
    print(f"  features : {clf.n_features_in_}")

    emit_header(tree, n_classes, args.output)


if __name__ == "__main__":
    main()
